# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Disable line length rule to allow flexibility
MD013: false

# Allow inline HTML (useful for badges, etc.)
MD033: false

# Allow duplicate heading text (common in documentation)
MD024: false

# Allow multiple top-level headings
MD025: false

# Allow trailing punctuation in headings
MD026: false

# Allow bare URLs
MD034: false
