name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run gitlint
        run: pre-commit run --hook-stage manual gitlint-ci
        continue-on-error: ${{ github.event_name	== 'pull_request' }} # Don't enforce gitlint in PRs
